logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Photomath]
rv-brand = "mod"
archive-dlurl = "https://lukemech.github.io/apksForRevanced/archive/com.microblink.photomath/com.microblink.photomath.html"
enabled = false

[Spotify]
rv-brand = "mod"
apkmirror-arch = "arm64-v8a"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
build-mode = "both"

[Youtube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "mod"
apkmirror-arch = "arm64-v8a"
build-mode = "both"
included-patches = "'Disable landscape mode' 'Enable music search' 'MaterialYou' 'Premium heading' 'Shorts outline button'"
excluded-patches = "'Custom branding icon Revancify Blue' 'Custom branding name YouTube'"
cli-source = "inotia00/revanced-cli"

[Youtube-Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "mod"
apkmirror-arch = "arm64-v8a"
build-mode = "both"
included-patches = ""
excluded-patches = "'Custom branding icon Revancify Blue' 'Custom branding name YouTube Music'"
cli-source = "inotia00/revanced-cli"

[Messenger]
rv-brand = "mod"
apkmirror-dlurl = "https://apkmirror.com/apk/facebook-2/messenger/"
apkmirror-arch = "arm64-v8a"
build-mode = "both"

[Tiktok]
rv-brand = "mod"
uptodown-dlurl = "https://tiktok.en.uptodown.com/android"
apkmirror-arch = "arm64-v8a"
build-mode = "both"
included-patches = "'SIM spoof'"

[Adobe-Lightroom]
rv-brand = "mod"
apkmirror-dlurl = "https://www.apkmirror.com/apk/adobe/lightroom/"
apkmirror-arch = "arm64-v8a + x86_64"
build-mode = "both"

[Meme-Generator]
rv-brand = "mod"
apkmirror-dlurl = "https://www.apkmirror.com/apk/zombodroid/meme-generator-free/"
apkmirror-arch = "arm64-v8a"
build-mode = "both"

[Facebook]
rv-brand = "mod"
uptodown-dlurl = "https://facebook.en.uptodown.com/android"
apkmirror-arch = "arm64-v8a"
build-mode = "both"

[Windy.com]
rv-brand = "mod"
apkmirror-dlurl = "https://www.apkmirror.com/apk/windyty-se/windy-wind-waves-and-hurricanes-forecast/"
apkmirror-arch = "arm64-v8a"
build-mode = "both"
