# SEE https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[main-config]
mount-delay = 1               # some low-end phones cannot mount apks on boot without a delay. increase to something like 20 if needed.
compression-level = 9         # compression level for module zips. between 1 and 9
enable-magisk-update = true   # set this to false if you do not want to receive updates from magisk app
parallel-jobs = 3             # max number of concurrent building jobs
update-prebuilts = true       # dont touch this
build-mindetach-module = true


[YouTube]
enabled = true                                                        # add 'enabled = false' key to entries to not build them
build-mode = "both"                                                   # 'both', 'apk' or 'module'
excluded-patches = "
always-autorepeat
comments
custom-branding
disable-auto-captions
disable-auto-player-popup-panels
disable-fullscreen-panels
enable-wide-searchbar
hide-album-cards
hide-artist-card
hide-autoplay-button
hide-captions-button
hide-cast-button
hide-crowdfunding-box
hide-email-address
hide-endscreen-cards
hide-info-cards
hide-my-mix
hide-time-and-seekbar
hide-watch-in-vr
hide-watermark
old-quality-layout
remove-player-button-background
tablet-mini-player
theme"                                        # whitespace seperated list of patches to exclude
included-patches = ""                                            # whitespace seperated list of patches to include
version = "auto"                                                      # 'auto', 'latest' or a custom one like '17.40.41'
exclusive-patches = false                                             # excludes all patches by default
microg-patch = ""
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "ytrv-magisk"
merge-integrations = true
rip-libs = true

[Music-arm64]
enabled = false

[Music-arm]
build-mode = "both"
app-name = "Music"
excluded-patches = "
tasteBuilder-remover"
included-patches = ""
version = "auto"
microg-patch = "music-microg-support"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
module-prop-name = "ytmusicrv-arm-magisk"
arch = "arm-v7a"

[Twitter]
enabled = false

[Reddit]
enabled = false

[Twitch]
enabled = false

[Tiktok]
enabled = false

[Spotify]
enabled = false

[TickTick]
enabled = false

[WarnWetter]
enabled = false

[Backdrops]
enabled = false

[Windy]
enabled = false
