[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
arch = "arm64-v8a"
version = "19.11.43"
included-patches = "'Spoof client' 'Minimized playback' 'Hide ads' 'Video ads' 'Custom branding' 'Change header' 'Change start page' 'Remember video quality'"
exclusive-patches = true
