logging-to-file = true
enable-magisk-update = false
build-mindetach-module = false

# extended
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "ReVanced Extended"

[YouTube]
build-mode = "apk"
excluded-patches = "custom-branding-name disable-haptic-feedback hide-cast-button hide-channel-watermark swipe-controls"
included-patches = "materialyou"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"

[YouTube_latest]
build-mode = "apk"
excluded-patches = "custom-branding-name disable-haptic-feedback hide-cast-button hide-channel-watermark swipe-controls"
included-patches = "materialyou"
version = "latest"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"

[Music-arm64]
build-mode = "apk"
excluded-patches = ""
included-patches = ""
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm64-v8a"

[Vanced-MicroG]
build-mode = "apk"
excluded-patches = "custom-branding-microg-revancify-blue hide-icon-from-launcher custom-branding-microg-name"
included-patches = "custom-branding-microg-revancify-red"
version = "latest"
apkmirror-dlurl = "https://www.apkmirror.com/apk/team-vanced/microg-youtube-vanced/"
