logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
build-mindetach-module = true

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[YouTube]
build-mode = "module"                                                   # 'both', 'apk' or 'module'
excluded-patches = "Always-Autorepeat Change-Package-Name Comments Copy-Video-Url Custom-Branding Disable-Shorts-On-Startup Disable-Zoom-Haptics Enable-Android-Debugging Enable-Debugging Export-All-Activities Hide-Shorts-Components Hide-Autoplay-Button Hide-Breaking-News-Shelf Hide-Captions-Button Hide-Cast-Button Hide-Email-Address Hide-Floating-Microphone-Button Hide-Player-Overlay Hide-Seekbar Hide-Timestamp Premium-Heading Remove-Player-Controls-Background Seekbar-Tapping Spoof-Wifi-Connection Tablet-Mini-Player Vanced-MicroG-Support Wide-Searchbar"                                                 # space-seperated patches to exclude (multiline strings are not supported)
included-patches = ""                                                 # space-seperated patches to include (non-excluded patches are included by default)
version = "18.23.35"                                                      # 'auto', 'latest', 'beta' or a custom one like '17.40.41'
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
