parallel-jobs = 1
logging-to-file = true
enable-magisk-update = false

[YT-REV-EX]
app-name = "YT"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "REV-EX"
build-mode = "apk"
excluded-patches = "custom-branding-youtube-name custom-branding-icon-revancify-blue custom-double-tap-length custom-playback-speed custom-seekbar-color enable-old-quality-layout enable-wide-search-bar language-switch return-youtube-dislike spoof-app-version swipe-controls"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
